/**
 * Model attribute names (camelCase) encrypted at rest before MySQL storage.
 * Foreign keys and fields used in SQL WHERE/GROUP/SUM stay plaintext (see PLAINTEXT_QUERY_FIELDS).
 */
export const PLAINTEXT_QUERY_FIELDS = {
  EodEntry: ['date', 'billingStatus'],
  DailyExpense: ['expenseDate'],
  Invoice: ['invoiceNumber', 'invoiceDate', 'paymentStatus', 'companyId', 'issuerCompanyId'],
  Payment: ['paymentDate', 'invoiceId'],
  DriverAdvance: ['advanceDate', 'status', 'salaryPeriodMonth', 'salaryPeriodYear', 'driverId'],
  EmployeeAdvance: ['advanceDate', 'status', 'salaryPeriodMonth', 'salaryPeriodYear', 'employeeId'],
  JobAssignment: ['assignmentDate', 'status'],
  InvoiceItem: ['invoiceId', 'eodEntryId'],
  AuditLog: ['userId', 'timestamp'],
  JobType: ['status'],
};

export const ENCRYPTED_MODEL_FIELDS = {
  User: ['mobile'],
  Driver: ['mobile', 'address', 'licenseNumber', 'notes'],
  Employee: ['mobile', 'email', 'roleDepartment', 'notes'],
  Company: [
    'contactPerson',
    'mobile',
    'email',
    'billingAddress',
    'gstNumber',
    'paymentTerms',
    'bankAccountNumber',
    'bankIfscCode',
    'bankAccountHolderName',
    'notes',
  ],
  Site: ['address', 'contactPerson', 'mobile', 'notes'],
  Vehicle: ['notes'],
  Role: ['name', 'description'],
  Permission: ['moduleName', 'action'],
  JobType: ['name', 'description', 'defaultUnit'],
  JobAssignment: [
    'outsideDriverName',
    'outsideDriverMobile',
    'outsideDriverVehicle',
    'fromSiteTemp',
    'toSiteTemp',
    'instructions',
    'expectedTrips',
    'companyRate',
    'driverCost',
    'dieselFuel',
  ],
  EodEntry: [
    'plannedTrips',
    'actualTrips',
    'ratePerTrip',
    'totalAmount',
    'extraCharges',
    'deductions',
    'dieselFuel',
    'expense',
    'remarks',
    'startTime',
    'endTime',
    'approvalDate',
  ],
  DailyExpense: ['amount', 'paidBy', 'paymentMode', 'receiptPath', 'notes'],
  Invoice: [
    'billToName',
    'billToAddress',
    'billToGst',
    'notes',
    'billingPeriodFrom',
    'billingPeriodTo',
    'totalTrips',
    'totalAmount',
    'extraCharges',
    'discount',
    'discountPercent',
    'taxRate',
    'cgstRate',
    'sgstRate',
    'taxAmount',
    'cgstAmount',
    'sgstAmount',
    'grandTotal',
  ],
  InvoiceItem: [
    'lineDate',
    'jobTypeName',
    'vehicleNumber',
    'driverName',
    'fromSite',
    'toSite',
    'actualTrips',
    'ratePerTrip',
    'amount',
  ],
  Payment: ['amount', 'paymentMode', 'referenceNumber', 'notes'],
  DriverAdvance: ['amount', 'givenBy', 'paymentMode', 'reason'],
  EmployeeAdvance: ['amount', 'givenBy', 'paymentMode', 'reason'],
  TemporarySite: ['address', 'contactPerson', 'mobile', 'reason'],
  AuditLog: ['module', 'action', 'recordId'],
};
